### PR TITLE
Report L1 datasets that were still in a task running state when the P…

### PR DESCRIPTION
**Pull request by sixy6e**
…BS job was terminated for whatever reason.

Essentially, Along with:

* level-1-pending.txt
* level-1-failed.txt
* level-1-done.txt

There will be another output named:

* level-1-running.txt

### CODE REVIEW

**Comment by sixy6e** [comment]
I'd recommend any batches that list level-1 datasets in the "running" state that they be looked into manually.

**Comment by dunkgray** [comment]
level-1-running.txt could be thought to mean that the scene is still being processed, which is not the case.  How about  level-1-pbs-fail.txt/level-1-nci-fail.txt or something like that?

**Comment by sixy6e** [comment]
I guess, but for the file to be produced, the job can't actually be running.

**Comment by dunkgray** [comment]
True. So if for the file to be produced the job can't actually be running I suggest labelling scenes as 'running' is confusing.

________________________________

**Comment by sixy6e** [comment]
I can see the confusing point as the names by themselves have no context unless one introduces it such as post job.
We could rename all files and use a longer filename so there is better context, as `pending` falls into the same situation as 'running' in that the words by themselves imply something is happening or about to happen.

This summary could also be wrapped into another JSONL document named "batch-<batch_id>-level1-final-state.jsonl".

The contents could then be:

```JSON
{"granule": "<granule_id>", "level": "info", "level1": "<level1_pathname", "state": "DONE"}
{"granule": "<granule_id>", "level": "info", "level1": "<level1_pathname", "state": "FAILED"}
{"granule": "<granule_id>", "level": "info", "level1": "<level1_pathname", "state": "PENDING"}
{"granule": "<granule_id>", "level": "info", "level1": "<level1_pathname", "state": "RUNNING"}
```

Whilst we still have "PENDING" and "RUNNING" as terms within the field named "state", there is some context about the contents of the file due to the file name.

**Comment by dunkgray** [comment]
Hi,
This description helped me understand the issue better.  These labels (done/failed/pending/running) are the final state of the processing.   The term final state is great.
level-1-failed.txt could be
 level-1-final_state-failed.txt
level-1-end-state-failed.txt
l1-final_state-failed.txt
I feel just tweaking the file name along the lines of level-1-final_state-[done|failed|pending|running].txt is all that is needed and a summary jsonl doc isn't needed.

Thanks Josh.

Cheers
Duncan

________________________________

**Comment by sixy6e** [comment]
Cool, I'll change them to be:

level-1-final_state-failed.txt
level-1-final_state-done.txt
level-1-final_state-pending.txt
level-1-final_state-running.txt

**Pull request merged**
